<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace ZMDev\Noxus\Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ZMDev.Noxus.pb.AppList</code>
 */
class AppList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .ZMDev.Noxus.pb.Application apps = 1;</code>
     */
    private $apps;

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>repeated .ZMDev.Noxus.pb.Application apps = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getApps()
    {
        return $this->apps;
    }

    /**
     * Generated from protobuf field <code>repeated .ZMDev.Noxus.pb.Application apps = 1;</code>
     * @param \ZMDev\Noxus\Pb\Application[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setApps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \ZMDev\Noxus\Pb\Application::class);
        $this->apps = $arr;

        return $this;
    }

}

