<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

namespace ZMDev\Noxus\Pb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ZMDev.Noxus.pb.ImageURL</code>
 */
class ImageURL extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string original = 1;</code>
     */
    private $original = '';
    /**
     * Generated from protobuf field <code>string xs = 2;</code>
     */
    private $xs = '';
    /**
     * Generated from protobuf field <code>string sm = 3;</code>
     */
    private $sm = '';
    /**
     * Generated from protobuf field <code>string md = 4;</code>
     */
    private $md = '';
    /**
     * Generated from protobuf field <code>string lg = 5;</code>
     */
    private $lg = '';

    public function __construct() {
        \GPBMetadata\Api::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string original = 1;</code>
     * @return string
     */
    public function getOriginal()
    {
        return $this->original;
    }

    /**
     * Generated from protobuf field <code>string original = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginal($var)
    {
        GPBUtil::checkString($var, True);
        $this->original = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string xs = 2;</code>
     * @return string
     */
    public function getXs()
    {
        return $this->xs;
    }

    /**
     * Generated from protobuf field <code>string xs = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setXs($var)
    {
        GPBUtil::checkString($var, True);
        $this->xs = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sm = 3;</code>
     * @return string
     */
    public function getSm()
    {
        return $this->sm;
    }

    /**
     * Generated from protobuf field <code>string sm = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSm($var)
    {
        GPBUtil::checkString($var, True);
        $this->sm = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string md = 4;</code>
     * @return string
     */
    public function getMd()
    {
        return $this->md;
    }

    /**
     * Generated from protobuf field <code>string md = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMd($var)
    {
        GPBUtil::checkString($var, True);
        $this->md = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lg = 5;</code>
     * @return string
     */
    public function getLg()
    {
        return $this->lg;
    }

    /**
     * Generated from protobuf field <code>string lg = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setLg($var)
    {
        GPBUtil::checkString($var, True);
        $this->lg = $var;

        return $this;
    }

}

